# ----------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License
# ----------------------------------------------------------------------
"""Contains the TypeInfo object"""

import os

import CommonEnvironment
from CommonEnvironment import Interface

# ----------------------------------------------------------------------
_script_fullpath                            = CommonEnvironment.ThisFullpath()
_script_dir, _script_name                   = os.path.split(_script_fullpath)
#  ----------------------------------------------------------------------

# ----------------------------------------------------------------------
class TypeInfo(Interface.Interface):
    """Creates constructs useful when generating code for a specific type"""

    # ----------------------------------------------------------------------
    # |
    # |  Public Types
    # |
    # ----------------------------------------------------------------------
    class Result(object):
        """Result information about a type when it is used in various scenarios."""

        # ----------------------------------------------------------------------
        def __init__(self, parameter_decl, validation_statements, invocation_statements):
            self.ParameterDecl              = parameter_decl
            self.ValidationStatements       = validation_statements
            self.InvocationStatements       = invocation_statements

        # ----------------------------------------------------------------------
        def __repr__(self):
            return CommonEnvironment.ObjectReprImpl(self)

    # ----------------------------------------------------------------------
    # |
    # |  Public Properties
    # |
    # ----------------------------------------------------------------------
    @Interface.abstractproperty
    def TypeName(self):
        """Name of the type"""
        raise Exception("Abstract property")

    @Interface.abstractproperty
    def CppType(self):
        """C++ type"""
        raise Exception("Abstract property")

    # ----------------------------------------------------------------------
    # |
    # |  Public Methods
    # |
    # ----------------------------------------------------------------------
    def __init__(
        self,
        custom_structs=None,
        custom_enums=None,
        is_optional=False,
        member_type=None,
        create_type_info_func=None,
    ):
        self.CustomStructs                  = custom_structs
        self.CustomEnums                    = custom_enums
        self.IsOptional                     = is_optional

    # ----------------------------------------------------------------------
    def __repr__(self):
        return CommonEnvironment.ObjectReprImpl(self)

    # ----------------------------------------------------------------------
    @Interface.abstractmethod
    def GetInputInfo(self, arg_name, invocation_template):
        """\
        Returns information about the type when used as an input argument.

        `invocation_template` is a template string that should be formatted with
        the argument values.
        """
        raise Exception("Abstract method")

    # ----------------------------------------------------------------------
    @Interface.abstractmethod
    def GetInputBufferInfo(self, arg_name, invocation_template):
        """\
        Returns information about the type when used as a buffer input argument.

        `invocation_template` is a template string that should be formatted with
        the argument values.
        """
        raise Exception("Abstract method")

    # ----------------------------------------------------------------------
    @Interface.abstractmethod
    def GetOutputInfo(
        self,
        arg_name,
        result_name="result",
        is_struct_member=False,
    ):
        """\
        Returns information about the type when used as an output argument.

        `result_name` is the name of the result returned by the shared library.
        """
        raise Exception("Abstract method")

    # ----------------------------------------------------------------------
    @Interface.abstractmethod
    def GetDestroyOutputInfo(
        self,
        arg_name="result",
    ):
        """\
        Returns information about the type when data generated by `GetOutputInfo` needs
        to be deleted by the caller.

        Return `None` if no explicit destruction functionality is required.
        """
        raise Exception("Abstract method")
