# ----------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License
parameters:
  agent_pool: ""
  agent_pool_container: ""
  agent_pool_is_custom: False # Set this value to True if the agent is part of a custom pool
  configuration: "" # Environment Activation Configuration
  esrp_connected_service_name: "" # Name of service connection to use for code signing (or empty string if code signing is not required)
  job_display_name: ""
  job_name_unique_id: ""
  operating_system: "" # Windows|Linux|MacOS
  test_only: False # Set to true to only run tests (no build)
  tester_code_coverage: False # Enable code coverage for tests
  tester_release_only: False # Only run release tests
  tester_build_only: False # Only build tests (but do not execute them)

jobs:
  - template: "_job_template.yaml"
    parameters:
      agent_pool: ${{ parameters.agent_pool }}
      agent_pool_container: ${{ parameters.agent_pool_container }}
      agent_pool_is_custom: ${{ parameters.agent_pool_is_custom }}
      job_name: BuildAndTest_${{ parameters.operating_system }}_${{ parameters.configuration }}_${{ parameters.agent_pool_container }}_${{ parameters.test_only }}_Job${{ parameters.job_name_unique_id }}
      job_display_name: "${{ parameters.job_display_name }}"
      operating_system: ${{ parameters.operating_system }}
      steps:
        - template: BuildAndTest.steps_template.yaml
          parameters:
            configuration: ${{ parameters.configuration }}
            esrp_connected_service_name: ${{ parameters.esrp_connected_service_name }}
            operating_system: ${{ parameters.operating_system }}
            test_only: ${{ parameters.test_only }}
            artifact_name: "${{ parameters.job_display_name }}"
            tester_code_coverage: ${{ parameters.tester_code_coverage }}
            tester_release_only: ${{ parameters.tester_release_only }}
            tester_build_only: ${{ parameters.tester_build_only }}
            build_only: ${{ parameters.build_only }}
            build_only_suffix: ${{ parameters.build_only_suffix }}
