# ----------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License
name: $(TeamProject)-$(BuildDefinitionName)-$(SourceBranchName)-$(Date:yyyy.MM.dd)-$(Rev:rr)

trigger: none

resources:

  containers:
    - container: universal_linux
      image: universal_linux
      endpoint: featurizerslibrarybuild

    - container: centos7
      image: centos7
      endpoint: featurizerslibrarybuild

stages:
  - template: "templates/BuildAndTest.prologue_stage_template.yaml"
    parameters:
      release_build: false
      prerelease_build_name: ""
      is_ci_build: false

  - stage: BuildAndTest_Stage
    displayName: "Build and Test:"
    dependsOn: Prologue_Stage

    jobs:
      # ----------------------------------------------------------------------
      # Official Builds

      - template: "templates/BuildAndTest.job_template.yaml"
        parameters:
          agent_pool: FeaturizersLibrary
          agent_pool_is_custom: true
          configuration: system_compiler
          job_display_name: "Ubuntu 16.04-x64-GCC"
          operating_system: Linux

  - stage: PostBuild_Stage
    displayName: "Post Build:"
    dependsOn: BuildAndTest_Stage

    jobs:
      - template: "templates/_job_template.yaml"
        parameters:
          agent_pool: FeaturizersLibrary
          agent_pool_is_custom: true
          job_name: Package_Job
          job_display_name: "Package"
          operating_system: Windows
          steps:
            - template: "BuildAndTest.package_steps_template.yaml"
              parameters:
                configuration: system_compiler
                operating_system: Windows
